server {
    listen 80;
    server_name localhost;

    # 1. Angular App ausliefern
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. Reverse Proxy für die API (Das ist die Magie!)
    location /api/ {

        proxy_pass http://backend:8080/api/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
