spring.application.name=eve-blueprint

# EVE API Configuration
eve.esi.base-url=https://esi.evetech.net/latest
eve.sso.client-id=${EVE_CLIENT_ID}
eve.sso.client-secret=${EVE_CLIENT_SECRET}
eve.sso.scopes=${EVE_SCOPES:publicData}

# Server Config
app.base.url=${BASE_URL}
app.frontend.url=${APP_FRONTEND_URL}
app.jwt.secret=${APP_JWT_SECRET}